### ISSUE TITLE
input number allows only single digit when dp == 0.

### ISSUE THREAD

**Issue by 2bbb** [automat/controlkit.js#14]
if we use NumberInput/Rage with setting {dp: 0}, then we can't input only single digit like 0 ~ 9.

**Comment by automat** [comment]
fixed with d795101ba9ea1734869dca4b41443e00a8d08f5a, thanks @2bbb

**Comment by 2bbb** [comment]
@automat 
no, maybe it is other problem.
this issue points what can't input number larger than 10 with keyboard input when set {dp: 0} .

**Comment by 2bbb** [comment]
thanks!

**Comment by automat** [comment]
Ok, will have a look at it. 
To be honest, inputs restricted to numbers do need some work.

**Comment by polyclick** [comment]
Started using controlkit today. Stumbled upon this problem immediately.
Can't input any numbers with more than 1 digit, even when keeping everything default.
