### ISSUE TITLE
Refresh ControlKit

### ISSUE THREAD

**Issue by msj121** [automat/controlkit.js#20]
My case: clicking different objects gives different inputs.

It would be nice to only show panels relevant if the object has the attribute.

The ability to empty control kit to allow restarting control kit from scratch on the page. This way re-add panels depending on the object. Is this currently possible?

**Comment by msj121** [comment]
Currently my solution is to keep the panel stored and call disable (not sure if this is the intended idea):
```
var controlKit = new ControlKit();
var panel = controlKit.addPanel(...);
return panel;

...

//When done with it:
panel.disable();
```

**Comment by M3kH** [comment]
Well since are [public methods](https://github.com/automat/controlkit.js/blob/master/lib/group/Panel.js#L472) I guess would be just good documented them.

**Comment by M3kH** [comment]
Is this valid?
