### ISSUE TITLE
insert into a particular dom element

### ISSUE THREAD

**Issue by Jinnified** [automat/controlkit.js#22]
is there a way to insert the control kit into a particular, say, div? rather than body?

**Comment by automat** [comment]
You can use the `parentDomElementId` option for specifying a target div.
```
var controlKit = new ControlKit({
    parentDomElementId : 'container'
});
```
```
<body>
<div id="some-div">
    <div id="container"></div> //ControlKit will replace this div
<div>
```

**Comment by Jinnified** [comment]
thanks,

another question, if i am using it with react, do i need to do something like destroy the controlKit in componentWillunMount() ?

**Comment by automat** [comment]
sorry, cant help with react-related questions.
