### ISSUE TITLE
destorying a controlkit instance

### ISSUE THREAD

**Issue by Jinnified** [automat/controlkit.js#23]
what's the correct way of destroying a controlkit instance?  say i have create an instance and want to destroy it later explicitly

const controlKit = new ControlKit({
    parentDomElementId: 'map1_ctrlkit'
 })

is there something like controlKit.destroy() ?

**Comment by Jinnified** [comment]
so i ended up change the source code, exposed 'initalised' variable, and set it to force, a big ugly hack, any suggestion would be appreciated

**Comment by automat** [comment]
there is currently no built-in way to do this, putting it on the feature requirements list.

**Comment by apertureless** [comment]
Are there any updates on this  ? @automat 
It is super annoying, because I work in a project with Hot Module Replacing and each time I change something I have to fully reload the page, as I am getting a `ControlKit is already initialized.` error.

**Comment by automat** [comment]
@apertureless if there would have been an update i would have logged it here. All work is going into rewrite branch, there will be no updates on master from my side

**Comment by Noext** [comment]
no update on this ?
