### ISSUE TITLE
No build found on rewrite branch, build-temp.js creates a build that doesn't export ControlKit

### ISSUE THREAD

**Issue by loredanacirstea** [automat/controlkit.js#41]
I wanted to add toggling to components/containers based on another component's value. I figured out how to do this with the `master` branch version, but then I found https://github.com/automat/controlkit.js/tree/rewrite . I wanted to use this branch for my changes.

After I ran:
```
npm install
node ./scripts/create-temp.js
node ./scripts/build-temp.js ./index.js
```

I opened `.tmp/index.htm`, but no `ControlKit` variable was available (the `bundle.js` script was loaded). What am I missing?

**Comment by automat** [comment]
`build-temp` is just a utility to run component test in `test/api`, it is not documented as script to build the library. Furthermore `rewrite` is in progress and will change. If you were able to patch in `master` please continue using that branch until the new version is out.

**Comment by loredanacirstea** [comment]
@automat ok, thank you the quick reply
