### ISSUE TITLE
Dynamically changing a button's label

### ISSUE THREAD

**Issue by cotejp** [automat/controlkit.js#5]
I just discovered ControlKit and I really like it. Congrats! 

Is there a way to dynamically change a button's label? I couldn't find how. Basically, I want to have a toggle-style start/stop button so I need to change the label.

Cheers!

P.S. It would be nice if callback functions received the component and value as parameters.

**Comment by automat** [comment]
Added `getButtonLabel()` `setButtonLabel()` with @0527fe998cae5b20cc67f01e383f9d2889aa8108, check [button-example](https://github.com/automat/controlkit.js/blob/master/examples/components/Button.html) for usage.
Callbacks will be bound to component with next version.

**Comment by cotejp** [comment]
Great! This is going to be very helpful.
